### ISSUE TITLE
add chromedriver support for redroid emulator

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#1]
investigate possibility to install latest and/or valid chromedriver inside redroid container
```
io.appium.java_client.NoSuchContextException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '83.0.4103'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELENDIK-XPS', ip: '192.168.2.99', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: https://qaprosoft.s3-us-wes..., appPackage: com.solvd.carinademoapplica..., carinaTestRunId: 6cc1c1e6-f021-4cc7-8a25-221..., databaseEnabled: false, desired: {app: https://qaprosoft.s3-us-wes..., carinaTestRunId: 6cc1c1e6-f021-4cc7-8a25-221..., deviceName: ANY, enableVideo: true, enableVnc: true, language: en, locale: US, platformName: android, provider: zebrunner}, deviceApiLevel: 30, deviceManufacturer: unknown, deviceModel: ReDroid, deviceName: android:5555, deviceScreenDensity: 320, deviceScreenSize: 720x1280, deviceUDID: android:5555, enableVideo: true, enableVnc: true, javascriptEnabled: true, language: en, locale: US, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: ANDROID, platformVersion: 11, provider: zebrunner, statBarHeight: 48, takesScreenshot: true, viewportRect: {height: 1136, left: 0, top: 48, width: 720}, warnings: {}, webStorageEnabled: false}
Session ID: a2abf0f1-3e70-42c9-98ce-94820cdcd23e
 at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:232)
 at com.qaprosoft.carina.demo.utils.MobileContextUtils.switchMobileContext(MobileContextUtils.java:48)
 at com.qaprosoft.carina.demo.MobileSampleTest.testWebView(MobileSampleTest.java:65)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
 at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
 at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
 at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
 at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
 at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '83.0.4103'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELENDIK-XPS', ip: '192.168.2.99', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.11'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: https://qaprosoft.s3-us-wes..., appPackage: com.solvd.carinademoapplica..., carinaTestRunId: 6cc1c1e6-f021-4cc7-8a25-221..., databaseEnabled: false, desired: {app: https://qaprosoft.s3-us-wes..., carinaTestRunId: 6cc1c1e6-f021-4cc7-8a25-221..., deviceName: ANY, enableVideo: true, enableVnc: true, language: en, locale: US, platformName: android, provider: zebrunner}, deviceApiLevel: 30, deviceManufacturer: unknown, deviceModel: ReDroid, deviceName: android:5555, deviceScreenDensity: 320, deviceScreenSize: 720x1280, deviceUDID: android:5555, enableVideo: true, enableVnc: true, javascriptEnabled: true, language: en, locale: US, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: ANDROID, platformVersion: 11, provider: zebrunner, statBarHeight: 48, takesScreenshot: true, viewportRect: {height: 1136, left: 0, top: 48, width: 720}, warnings: {}, webStorageEnabled: false}
Session ID: a2abf0f1-3e70-42c9-98ce-94820cdcd23e
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:156)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
 at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
 at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
 at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:229)
 ... 17 more
```

**Comment by vdelendik** [comment]
tested on my own. webview and mobile web tests are supported now on android emulator
