### ISSUE TITLE
capture panic on wda start and exit from container with error code

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#111]
during wda kill/startup we can see below panic. it means that go ios can't connect to device.
let's capture such output asap and exit from container. as of now it try to start wda and raise exception as WDA_HOST can't be determined in 15-30s
```
root@fb9d8499b4e6:~# [30/04/2022 04:24:34] Killing existing WebDriverAgent application if any
{"channel_id":"com.apple.instruments.server.services.processcontrol","error":"Timed out waiting for response for message:5 channel:0","level":"error","msg":"failed requesting channel","time":"2022-04-30T04:24:39-07:00"}
{"channel_id":"com.apple.instruments.server.services.deviceinfo","error":"Timed out waiting for response for message:5 channel:0","level":"error","msg":"failed requesting channel","time":"2022-04-30T04:24:44-07:00"}
{"level":"error","msg":"DeviceConnection failed writing 204 bytes, only 0 sent","time":"2022-04-30T04:24:44-07:00"}
{"level":"error","msg":"Failed sending: write unix @-\u003e/var/run/usbmuxd: write: broken pipe","time":"2022-04-30T04:24:44-07:00"}
{"channel_id":"com.apple.instruments.server.services.deviceinfo","error":"write unix @-\u003e/var/run/usbmuxd: write: broken pipe","level":"info","methodselector":"runningProcesses","msg":"failed starting invoking method","time":"2022-04-30T04:24:44-07:00"}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/danielpaulus/go-ios/ios/instruments.DeviceInfoService.ProcessList({0xc00052a120, 0xc000496940})
        /home/runner/work/go-ios/go-ios/ios/instruments/processlist.go:26 +0x137
main.Main()
        /home/runner/work/go-ios/go-ios/main.go:493 +0x1551
main.main()
        /home/runner/work/go-ios/go-ios/main.go:46 +0x17
[30/04/2022 04:24:44] Starting WebDriverAgent application on port 8100
```

**Comment by vdelendik** [comment]
as only we face with this issue the only solution so far is device reboot

**Comment by vdelendik** [comment]
let's analyze how it works with appium 2.0 where we simplified wda reinstall and restarts a lot. Hopefully we might close it as can't reproduce and forget.

**Comment by vdelendik** [comment]
still repro for the AppleTV devices. closing this one as dupe of new #241 related to AppleTV only.

**Comment by dhreben** [comment]
Closed
