### ISSUE TITLE
Add ability to delete data from Android devices after restarting the container

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#123]
After starting 1 test run (Mi_Note_10_Lite) more than 250 video files were saved on one device, so its memory was soon full, it makes sense to сlean the data after restarting the container.

```
2022-04-26T14:51:22.469Z INF/device:resources:minicap 486 [ed6bd1ab] Installing "/opt/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-30/minicap.so" as "/data/local/tmp/minicap.so"
2022-04-26T14:51:22.469Z INF/device:resources:minicap 486 [ed6bd1ab] Installing "/opt/node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch/minicap.apk" as "/data/local/tmp/minicap.apk"
Unhandled rejection Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:376:12)
    at Connection.write (/opt/node_modules/@devicefarmer/adbkit/lib/adb/connection.js:94:17)
    at Sync._sendCommandWithLength (/opt/node_modules/@devicefarmer/adbkit/lib/adb/sync.js:313:28)
    at writeNext (/opt/node_modules/@devicefarmer/adbkit/lib/adb/sync.js:180:19)
    at tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Unhandled rejection Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:376:12)
    at Connection.write (/opt/node_modules/@devicefarmer/adbkit/lib/adb/connection.js:94:17)
    at Sync._sendCommandWithLength (/opt/node_modules/@devicefarmer/adbkit/lib/adb/sync.js:313:28)
    at writeNext (/opt/node_modules/@devicefarmer/adbkit/lib/adb/sync.js:180:19)
    at tryCatcher (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/opt/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

```

**Comment by dhreben** [comment]
Closed
