### ISSUE TITLE
add uiautomator2 server status health check

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#162]
to avoid socker hangs and crashing of the application we can implement uiautomator2 heltchcheck and do it before session startup.
in case of the problem we have to crash and initiate containers restart. Still uner the question if regular restart helps for it (need confirmation)
```
2023-02-02 00:39:15:549 [Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
2023-02-02 00:39:15:681 [WD Proxy] Matched '/status' to command name 'getStatus'
2023-02-02 00:39:15:681 [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
2023-02-02 00:39:15:702 [WD Proxy] socket hang up
2023-02-02 00:39:16:579 [Instrumentation] Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server):
2023-02-02 00:39:16:579 [Instrumentation] java.lang.ExceptionInInitializerError
2023-02-02 00:39:16:579 [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:41)
2023-02-02 00:39:16:579 [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.<init>(MjpegScreenshotServer.java:35)
2023-02-02 00:39:16:579 [Instrumentation] 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
2023-02-02 00:39:16:579 [Instrumentation] 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
2023-02-02 00:39:16:579 [Instrumentation] 	... 27 trimmed
2023-02-02 00:39:16:580 [Instrumentation] Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@448386falready registered!
2023-02-02 00:39:16:580 [Instrumentation] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2446)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.os.Parcel.createException(Parcel.java:2422)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.os.Parcel.readException(Parcel.java:2405)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.os.Parcel.readException(Parcel.java:2347)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:514)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:324)
2023-02-02 00:39:16:580 [Instrumentation] 	at android.app.UiAutomation.connect(UiAutomation.java:289)
2023-02-02 00:39:16:581 [Instrumentation] 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2224)
2023-02-02 00:39:16:581 [Instrumentation] 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
2023-02-02 00:39:16:581 [Instrumentation] 	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
2023-02-02 00:39:16:581 [Instrumentation] 	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
2023-02-02 00:39:16:581 [Instrumentation] 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
2023-02-02 00:39:16:581 [Instrumentation] 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:33)
2023-02-02 00:39:16:581 [Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.<init>(CustomUiDevice.java:70)
2023-02-02 00:39:16:581 [Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:80)
2023-02-02 00:39:16:581 [Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.<clinit>(MjpegScreenshotStream.java:43)
2023-02-02 00:39:16:581 [Instrumentation] 	... 32 more
2023-02-02 00:39:16:666 [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
2023-02-02 00:39:16:666 [Instrumentation] INSTRUMENTATION_CODE: 0

```

**Comment by vdelendik** [comment]
removed milestone to observe how it's going in appium 2.0

**Comment by vdelendik** [comment]
similar to #183

**Comment by vdelendik** [comment]
closing as can't reproduce in 2.0.x
