### ISSUE TITLE
stop recording on the `invalid session id` detection

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#204]
```
2023-08-09 12:10:00:169 - [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001a5df9588 3F529C4A-5003-3E5D-84F7-03806108055E + 38280\n\t1   libobjc.A.dylib                     0x000000019f0f5050 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001a5f52f94 3F529C4A-5003-3E5D-84F7-03806108055E + 1453972\n\t3   WebDriverAgentLib                   0x0000000102b209b8 -[FBRoute raiseNoSessionException] + 80\n\t4   WebDriverAgentLib                   0x0000000102b2090c -[FBRoute decorateRequest:] + 244\n\t5   WebDriverAgentLib                   0x0000000102b1fda8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 92\n\t6   WebDriverAgentLib                   0x0000000102b0b9f8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408\n\t7   WebDriverAgentLib                   0x0000000102b42504 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t8   WebDriverAgentLib                   0x0000000102b42ff4 __72...
2023-08-09 12:10:00:171 - [debug] [W3C] [W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
2023-08-09 12:10:00:198 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)] Encountered internal error running command: Session does not exist[[[--udid d6afc6b3a65584ca0813eb8957c6479b9b6ebb11 --name iPhone_8_Plus --sessionId d9b51a4b-d735-409e-a8e0-38fc2324abe5]]]
2023-08-09 12:10:00:199 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)] NoSuchDriverError: Session does not exist
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at errorFromW3CJsonCode (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1040:25)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at ProxyRequestError.getActualError (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:909:14)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at JWProxy.command (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at XCUITestDriver.proxyCommand (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:112:35)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at getScreenshotFromWDA (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:12:20)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at wrapped (/usr/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:95:13)
2023-08-09 12:10:00:200 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at retry (/usr/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:68:13)
2023-08-09 12:10:00:201 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at retryInterval (/usr/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:105:10)
2023-08-09 12:10:00:201 - [debug] [XCUITestDriver@85fa (d9b51a4b)] [XCUITestDriver@85fa (d9b51a4b)]     at XCUITestDriver.getScreenshot (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/screenshots.js:46:12)
2023-08-09 12:10:00:201 - [HTTP] [HTTP] <-- GET /wd/hub/session/d9b51a4b-d735-409e-a8e0-38fc2324abe5/screenshot 404 1102 ms - 1395
```

**Comment by vdelendik** [comment]
moved to 2.1 as implementation of the detection is not so simple and too risky on this phase. we can put it as known issue for v2.0.
i.e. in case of any wda crash etc we couldn't generate valid video recording.

**Comment by vdelendik** [comment]
@azarouski, please share results of your research of using separate recording service. if it is valid we can close it as won't fix.

**Comment by dhreben** [comment]
Won't fix
