### ISSUE TITLE
Original error: fs is not defined

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium#352]
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the service http://localhost:4723/wd/hub. Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: fs is not defined[[[--udid R..MG --name Samsung_Galaxy_S23_Plus --sessionId d6e82236-4721-4938-8108-7c10c43daf25]]] 
Host info: host: '897c3ca5f9f4', ip: '172.18.0.7'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-97-generic', java.version: '11.0.21'
Driver info: driver.version: unknown
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-97-generic', java.version: '11.0.21'
Driver info: driver.version: unknown
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.2.0-1015-aws', java.version: '11.0.16'
Driver info: driver.version: unknown
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.214-160.339.amzn2.x86_64', java.version: '17.0.7'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:safariInitialUrl=http://appium.io/, appium:devicePool=ANY, appium:newCommandTimeout=60, appium:locale=US, appium:appInstallStrategy=parallel, appium:simpleIsVisibleCheck=true, appium:autoAcceptAlerts=false, appium:language=en, appium:remoteAppsCacheLimit=0, appium:noSign=true, appium:startIWDP=false, appium:automationName=UIAutomator2, appium:fullReset=true, appium:autoGrantPermissions=false, appium:appPushTimeout=90000, appium:appActivity=com.mobilecreditcards.MainActivity, appium:deviceName=ANY, platformName=ANDROID, appium:app=https://storage.googleapis.com/bitrise-build-storage-prod-with-retention-policy/apps/dbac9175c11616d6/builds/7fb7ab20-2dae-4c76-8bde-8d0025f0573f/artifacts/b7498351ee2e8f1a/nerdwallet-android-staging-116930.apk?Expires=1710082737&GoogleAccessId=build-artifact-sa-prod%40ip-web-monolith-prod.iam.gserviceaccount.com&Signature=RBjqwosrbYuY1afjcpWrLNf8matfujoiWWYudSHwKmaAEnLYZi1xiEpbG5v%2FDXD82PHsnolRdmnCPCYmc2JQk0t7buRfaImCFI0V%2F9rp94%2FcnVg8wURnfbSSPIkJrWIECjuoAVMciSCzt5ChZeGRjJsuwvGP85pZiKZ4WxEcjfnNnPFIwCDzpF%2B4M7d8Yn%2FKQn%2F7pSe4odfmvbAqAz4hrMTvw0xe1F8Qx3KOpi%2Bxt6oTy%2BI0juNJ7yaGi%2BD5cnBVNbYtNdR8dpJBq5DCLzcrfN7%2BXj%2F6f9YkgDPGwlugxLLKZvKrNAp8i6mV5jqyYsXVucp3K1ekku9zA2bNQoSR9g%3D%3D, appium:appPackage=com.mobilecreditcards.staging}], desiredCapabilities=Capabilities {appium:app: https://storage.googleapis/...., appium:appActivity: com.mobilecreditcards.MainA..., appium:appInstallStrategy: parallel, appium:appPackage: com.mobilecreditcards.staging, appium:appPushTimeout: 90000, appium:autoAcceptAlerts: false, appium:autoGrantPermissions: false, appium:automationName: UIAutomator2, appium:deviceName: ANY, appium:devicePool: ANY, appium:fullReset: true, appium:language: en, appium:locale: US, appium:newCommandTimeout: 60, appium:noSign: true, appium:remoteAppsCacheLimit: 0, appium:safariInitialUrl: http://appium.io/, appium:simpleIsVisibleCheck: true, appium:startIWDP: false, platformName: ANDROID}}]
Capabilities {appium:app: bitrise://dbac9175c11616d6/..., appium:appActivity: com.mobilecreditcards.MainA..., appium:appInstallStrategy: parallel, appium:appPackage: com.mobilecreditcards.staging, appium:appPushTimeout: 90000, appium:autoAcceptAlerts: false, appium:autoGrantPermissions: false, appium:automationName: UIAutomator2, appium:deviceName: ANY, appium:devicePool: ANY, appium:fullReset: true, appium:language: en, appium:locale: US, appium:newCommandTimeout: 60, appium:noSign: true, appium:remoteAppsCacheLimit: 0, appium:safariInitialUrl: http://appium.io/, appium:simpleIsVisibleCheck: true, appium:startIWDP: false, platformName: ANDROID}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
	at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at com.zebrunner.carina.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:109)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at io.appium.java_client.AppiumDriver.startSession$original$uZ3Vn4s7(AppiumDriver.java:274)
	at io.appium.java_client.AppiumDriver.startSession$original$uZ3Vn4s7$accessor$BTE0nfNl(AppiumDriver.java)
	at io.appium.java_client.AppiumDriver$auxiliary$NPIqZdfK.run(Unknown Source)
	at com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:42)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:103)
	at com.zebrunner.carina.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:111)
	at com.zebrunner.carina.webdriver.core.factory.DriverFactory.create(DriverFactory.java:89)
	at com.zebrunner.carina.webdriver.IDriverPool.createDriver(IDriverPool.java:376)
	at com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:122)
	at com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:85)
	at com.zebrunner.carina.webdriver.IDriverPool.getDriver(IDriverPool.java:73)
	at com.zebrunner.carina.utils.factory.ICustomTypePageFactory.initPage(ICustomTypePageFactory.java:73)
	at com.nerdwallet.qa.mobile.mobilehome.services.AuthService.clickLoginButton(AuthService.java:294)
	at com.nerdwallet.qa.mobile.mobilehome.services.AuthService.passLoginScreen(AuthService.java:133)
	at com.nerdwallet.qa.mobile.mobilehome.services.AuthService.login(AuthService.java:84)
	at com.nerdwallet.qa.mobile.creditscore.creditfactors.factors.RecentInquiriesTest.twoInquiriesInDifferentStateTest(RecentInquiriesTest.java:232)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by vdelendik** [comment]
`appium:2.0.13-beta1` is ready for testing
@dhreben ^^^
